### ISSUE TITLE
1.3 recompile needed!

### ISSUE THREAD

**Issue by etmoonshade** [Olympic1/Unofficial_LTech#15]
I'll check and see if the existing version works on 1.3 of course, but just tossing this out here (so as not to bump the forum thread for no reason.)

**Comment by etmoonshade** [comment]
Yup, recompile or bugfix needed. Logs attached. :)
Basically, it crashes while it's trying to load. Specifically when processing... you guessed it, the damn camera. :V

[2017-07-04_154834.zip](https://github.com/Olympic1/L-Tech/files/1123153/2017-07-04_154834.zip)

**Comment by Olympic1** [comment]
Done in dev. Working out some last bugs
