### ISSUE TITLE
NREs causing issues with other mods

### ISSUE THREAD

**Issue by mheguy** [Olympic1/Unofficial_LTech#9]
From RealGecko in http://forum.kerbalspaceprogram.com/index.php?/topic/143433-ksp-12-kei-kerbin-environmental-institute120-2016-10-12/&do=findComment&comment=2801938 and the ensuing thread it seems throwing null refs causes issues for mods that rely on science experiments including xScience and KEI.

**Comment by linuxgurugamer** [comment]
nope, bug not found yet

**Comment by linuxgurugamer** [comment]
First problem is with KEI, I found a bug and submitted a PR to fix it.  Still looking at this, it is something to do with the experimentID being null

**Comment by linuxgurugamer** [comment]
Found the problem, just need to fix it in a good way

**Comment by linuxgurugamer** [comment]
So [x]Science has the fix in place.  for some reason, the experimentID is null at this place in KEI, I haven't yet figured out why

**Comment by linuxgurugamer** [comment]
Solved, the module SkyLabCore inherits ModuleScienceExperiment, which needs the experimentID set.
I pushed a change to the Skylab.cfg file
